// pets-data.js - 侍从图鉴数据（共45个）
// 数据来源：官方图鉴
const PETS_DATA = [
  {
    "id": "pet_1",
    "name": "觉醒·泰拉勒",
    "class": "通用",
    "quality": "觉醒·神话",
    "bonds": "天使降临",
    "icon": "assets/pets/content_28.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 1
  },
  {
    "id": "pet_2",
    "name": "觉醒·奶牛之王",
    "class": "通用",
    "quality": "觉醒·神话",
    "bonds": "主仆关系",
    "icon": "assets/pets/content_29.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 2
  },
  {
    "id": "pet_3",
    "name": "觉醒·面山",
    "class": "通用",
    "quality": "觉醒·神话",
    "bonds": "类人组合",
    "icon": "assets/pets/content_30.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 3
  },
  {
    "id": "pet_4",
    "name": "觉醒·斗瓦尔",
    "class": "通用",
    "quality": "觉醒·神话",
    "bonds": "森林隐者",
    "icon": "assets/pets/content_31.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 4
  },
  {
    "id": "pet_5",
    "name": "觉醒·玛瑟尔",
    "class": "通用",
    "quality": "觉醒·神话",
    "bonds": "天使降临",
    "icon": "assets/pets/content_32.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 5
  },
  {
    "id": "pet_6",
    "name": "觉醒·墨特",
    "class": "通用",
    "quality": "觉醒·神话",
    "bonds": "三魔神",
    "icon": "assets/pets/content_33.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 6
  },
  {
    "id": "pet_7",
    "name": "觉醒·莉娅布罗",
    "class": "通用",
    "quality": "觉醒·神话",
    "bonds": "三魔神",
    "icon": "assets/pets/content_34.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 7
  },
  {
    "id": "pet_8",
    "name": "觉醒·霸迭",
    "class": "通用",
    "quality": "觉醒·神话",
    "bonds": "三魔神",
    "icon": "assets/pets/content_35.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 8
  },
  {
    "id": "pet_9",
    "name": "觉醒·爱露",
    "class": "通用",
    "quality": "觉醒·神话",
    "bonds": "力量与美貌",
    "icon": "assets/pets/content_37.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 9
  },
  {
    "id": "pet_10",
    "name": "觉醒·魔蛋",
    "class": "通用",
    "quality": "觉醒·神话",
    "bonds": "力量与美貌",
    "icon": "assets/pets/content_39.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 10
  },
  {
    "id": "pet_11",
    "name": "觉醒·安娜特",
    "class": "通用",
    "quality": "觉醒·神话",
    "bonds": "剧毒与阴谋",
    "icon": "assets/pets/content_42.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 11
  },
  {
    "id": "pet_12",
    "name": "觉醒·奥黛丽",
    "class": "通用",
    "quality": "觉醒·神话",
    "bonds": "暂无",
    "icon": "assets/pets/content_45.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 12
  },
  {
    "id": "pet_13",
    "name": "泰拉勒",
    "class": "通用",
    "quality": "神话",
    "bonds": "天使降临",
    "icon": "assets/pets/content_6.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 13
  },
  {
    "id": "pet_14",
    "name": "奶牛之王",
    "class": "通用",
    "quality": "神话",
    "bonds": "主仆关系",
    "icon": "assets/pets/content_1.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 14
  },
  {
    "id": "pet_15",
    "name": "面山",
    "class": "通用",
    "quality": "神话",
    "bonds": "类人组合",
    "icon": "assets/pets/content_2.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 15
  },
  {
    "id": "pet_16",
    "name": "斗瓦尔",
    "class": "通用",
    "quality": "神话",
    "bonds": "森林隐者",
    "icon": "assets/pets/content_3.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 16
  },
  {
    "id": "pet_17",
    "name": "玛瑟尔",
    "class": "通用",
    "quality": "神话",
    "bonds": "天使降临",
    "icon": "assets/pets/content_4.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 17
  },
  {
    "id": "pet_18",
    "name": "墨特",
    "class": "通用",
    "quality": "神话",
    "bonds": "三魔神",
    "icon": "assets/pets/content_5.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 18
  },
  {
    "id": "pet_19",
    "name": "莉娅布罗",
    "class": "通用",
    "quality": "神话",
    "bonds": "三魔神",
    "icon": "assets/pets/content_7.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 19
  },
  {
    "id": "pet_20",
    "name": "霸迭",
    "class": "通用",
    "quality": "神话",
    "bonds": "三魔神",
    "icon": "assets/pets/content_8.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 20
  },
  {
    "id": "pet_21",
    "name": "爱露",
    "class": "通用",
    "quality": "神话",
    "bonds": "力量与美貌",
    "icon": "assets/pets/content_36.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 21
  },
  {
    "id": "pet_22",
    "name": "魔蛋",
    "class": "通用",
    "quality": "神话",
    "bonds": "力量与美貌",
    "icon": "assets/pets/content_38.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 22
  },
  {
    "id": "pet_23",
    "name": "安娜特",
    "class": "通用",
    "quality": "神话",
    "bonds": "剧毒与阴谋",
    "icon": "assets/pets/content_40.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 23
  },
  {
    "id": "pet_24",
    "name": "贝利尔",
    "class": "通用",
    "quality": "神话",
    "bonds": "剧毒与阴谋",
    "icon": "assets/pets/content_41.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 24
  },
  {
    "id": "pet_25",
    "name": "奥黛丽",
    "class": "通用",
    "quality": "神话",
    "bonds": "暂无",
    "icon": "assets/pets/content_44.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 25
  },
  {
    "id": "pet_26",
    "name": "魔钩肥",
    "class": "通用",
    "quality": "传奇",
    "bonds": "大块头",
    "icon": "assets/pets/content_9.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 26
  },
  {
    "id": "pet_27",
    "name": "枯骨王",
    "class": "通用",
    "quality": "传奇",
    "bonds": "鬼怪",
    "icon": "assets/pets/content_10.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 27
  },
  {
    "id": "pet_28",
    "name": "幽灵法师",
    "class": "通用",
    "quality": "传奇",
    "bonds": "主仆关系",
    "icon": "assets/pets/content_11.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 28
  },
  {
    "id": "pet_29",
    "name": "魔刃",
    "class": "通用",
    "quality": "传奇",
    "bonds": "天使降临",
    "icon": "assets/pets/content_12.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 29
  },
  {
    "id": "pet_30",
    "name": "狗头人萨满",
    "class": "通用",
    "quality": "传奇",
    "bonds": "野蛮部落",
    "icon": "assets/pets/content_13.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 30
  },
  {
    "id": "pet_31",
    "name": "狗头人卫士",
    "class": "通用",
    "quality": "史诗",
    "bonds": "野蛮部落",
    "icon": "assets/pets/content_14.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 31
  },
  {
    "id": "pet_32",
    "name": "爆烈战士",
    "class": "通用",
    "quality": "史诗",
    "bonds": "透明小分队",
    "icon": "assets/pets/content_15.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 32
  },
  {
    "id": "pet_33",
    "name": "咒蚀先知",
    "class": "通用",
    "quality": "史诗",
    "bonds": "透明小分队",
    "icon": "assets/pets/content_16.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 33
  },
  {
    "id": "pet_34",
    "name": "迷雾蛛后",
    "class": "通用",
    "quality": "史诗",
    "bonds": "森林隐者",
    "icon": "assets/pets/content_17.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 34
  },
  {
    "id": "pet_35",
    "name": "飘飘",
    "class": "通用",
    "quality": "史诗",
    "bonds": "鬼怪",
    "icon": "assets/pets/content_18.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 35
  },
  {
    "id": "pet_36",
    "name": "荒原狼",
    "class": "通用",
    "quality": "稀有",
    "bonds": "疯狂动物城",
    "icon": "assets/pets/content_19.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 36
  },
  {
    "id": "pet_37",
    "name": "吞噬怪",
    "class": "通用",
    "quality": "稀有",
    "bonds": "透明小分队",
    "icon": "assets/pets/content_20.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 37
  },
  {
    "id": "pet_38",
    "name": "堕落枪手",
    "class": "通用",
    "quality": "稀有",
    "bonds": "类人组合",
    "icon": "assets/pets/content_21.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 38
  },
  {
    "id": "pet_39",
    "name": "沙刺蜂",
    "class": "通用",
    "quality": "稀有",
    "bonds": "疯狂动物城",
    "icon": "assets/pets/content_22.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 39
  },
  {
    "id": "pet_40",
    "name": "巨石魔",
    "class": "通用",
    "quality": "稀有",
    "bonds": "大块头",
    "icon": "assets/pets/content_23.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 40
  },
  {
    "id": "pet_41",
    "name": "小骨战士",
    "class": "通用",
    "quality": "精英",
    "bonds": "鬼怪",
    "icon": "assets/pets/content_24.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 41
  },
  {
    "id": "pet_42",
    "name": "沙地幼虫",
    "class": "通用",
    "quality": "精英",
    "bonds": "疯狂动物城",
    "icon": "assets/pets/content_25.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 42
  },
  {
    "id": "pet_43",
    "name": "堕落弓手",
    "class": "通用",
    "quality": "精英",
    "bonds": "类人组合",
    "icon": "assets/pets/content_26.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 43
  },
  {
    "id": "pet_44",
    "name": "钉刺魔",
    "class": "通用",
    "quality": "精英",
    "bonds": "疯狂动物城",
    "icon": "assets/pets/content_27.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 44
  },
  {
    "id": "pet_45",
    "name": "觉醒·贝利尔",
    "class": "通用",
    "quality": "未知",
    "bonds": "剧毒与阴谋",
    "icon": "assets/pets/content_43.png",
    "desc": "",
    "source": "官方图鉴",
    "detail_img": "",
    "sort": 45
  }
];
